name: Deploy to Cloud Run

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Build and Push to Container Registry
      run: |
        docker build -t gcr.io/usim-web-project/usim-web:${{ github.sha }} .
        docker push gcr.io/usim-web-project/usim-web:${{ github.sha }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: usim-web
        image: gcr.io/usim-web-project/usim-web:${{ github.sha }}
        region: asia-southeast1
        allow-unauthenticated: true
        env_vars: |
          NODE_ENV=production
