# Thay đổi từ:
- name: Deploy to Cloud Run
  uses: google-github-actions/deploy-cloudrun@v1
  with:
    service: usim-web
    source: .
    region: asia-southeast1
    allow-unauthenticated: true
    env_vars: |
      NODE_ENV=production

# Thành:
- name: Build and Push to Container Registry
  run: |
    docker build -t gcr.io/usim-web-project/usim-web:${{ github.sha }} .
    docker push gcr.io/usim-web-project/usim-web:${{ github.sha }}

- name: Deploy to Cloud Run
  uses: google-github-actions/deploy-cloudrun@v1
  with:
    service: usim-web
    image: gcr.io/usim-web-project/usim-web:${{ github.sha }}
    region: asia-southeast1
    allow-unauthenticated: true
    env_vars: |
      NODE_ENV=production
